# Generated by Django 5.2.9 on 2025-12-03 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_multi_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='attendance_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='quiz_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='api.participant')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='rating', max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_questions', to='api.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
                ('session_date', models.DateField()),
                ('session_start', models.TimeField()),
                ('session_end', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.event')),
            ],
            options={
                'ordering': ['order', 'session_date', 'session_start'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(default='multiple_choice', max_length=50)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
